sudo: required
language: node_js
node_js:
- '4.1'
git:
  depth: 1
env:
  DOCKER_COMPOSE_VERSION: 1.5.0
services:
- docker
before_install:
- npm install
- export NODE_ENV=test
- webpack
- npm test
- export NODE_ENV=production
- webpack
install: true
script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t georgebatalinski/rate-instructor-demo:latest .
- docker push georgebatalinski/rate-instructor-demo
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJ7M77GSCZWSF7EKA
  secret_access_key:
    secure: zcPCQUzTjpCF/Gfny3zmcilRrG+ZG2TM9+Uxr6Lk3d1fTSG/KaV/3N+vnbbwBBXSZhapWl7rJ/txmZiTZtKYnSj+GT/LGBR4ZlACnzlq/kib22ijsk35cQGKhkkG3CT6EtYHQAXHwHw6Pfxt4jBRZ+ZxOrHVgetAL2+R507ad0dGSdAgSwPd4I9avxr30tHjLMjzo2sK0nIuI0yNYPdPZHVhI2n//zBmjioWwqYIGvzQ86heNmr0TzBVRopmQFbbfgfy9UuGv1wsRsiGIbsPX5Ee9aclxUoCYCv69LXTbz543hMg2YRH6LN9GHRNfFVjlSp8SqPC9p7v1n1zadBz0YrMcctbyGM32Ssq0iQKHm1eiC5oEaA4l3K7hTP6Hp/1Xe8+QFnIy7iNmHw/KPs3mM6KXBoHH1qw8rUIKfr4RiD4tXg9nujN1lvW76mKv0Im5kVLbgAgAulQD4mCgWPNxk2AGpzI/9381SjHNPtLTTFMc1tZ8bLRzLTdwPdPUYF71cAy1dePvGTfcFiOwJ1YunzlspJJVHjGj8GUqkRJqLtqN5mLt7MMBNtaVrmH05HgCgA7Nm0SD1nfWuO+xRrWLI5HZVwGxMfJ/hFJVgvY56nZq9TfczVK7SVjuIlXwzj7+lD16wCuW3eeJb5hMpnVMGIp1RbaY7SP3Y3DQa5J4yY=
  region: us-east-1
  app: pharos_django_dev
  env: pharos_test_env
  on:
    repo: countzen2000/ri-demo-docker-travis-aws
